language: node_js
node_js:
  - 8
  - 9
  - 10

before_script:
  # replace environment variable
  - cp app.example.yaml app.yaml
  - envsubst < app.yaml > app.yaml

before_install:
  # decrpty key file
  - openssl aes-256-cbc -K $encrypted_623b127796c5_key -iv $encrypted_623b127796c5_iv -in gce.json.enc -out gce.json -d
  # install dependencies
  - npm i -g npm@latest
  - npm install -g typescript
  - npm install

install:
  # build production version to dist/ folder
  - npm run build

deploy:
  provider: gae
  project: $PROJECT_ID_PRODUCTION
  keyfile: gce.json
  verbosity: debug
  on:
    branch: master
    node_js: "10"
