language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
git:
  depth: 5

before_install:
  - npm i -g npm@latest
  - npm install -g typescript
  - npm install

install:
  - npm run build
  - cp ormconfig.example.json ormconfig.json
  - sed -i "s/original/new/g" file.txt
  - echo $ORMCONFIG_KEY_FILE_PRODUCTION > ormconfig.json

deploy:
  provider: script
  project: $PROJECT_ID_PRODUCTION
  keyfile: gce.json
  verbosity: debug
  on:
    branch: master
    node_js: "10"
