language: node_js
node_js:
  - "8"
  - "9"
  - "10"

before_install:
  - npm i -g npm@latest
  - npm install -g typescript
  - npm install

install:
  - npm run build

deploy:
  provider: gae
  project: $PROJECT_ID_PRODUCTION
  keyfile: gce.json
  verbosity: debug
  on:
    branch: master
    node_js: "10"
